// Avatar options. Kid-friendly set + grown-up set (only shown if
// the user is flagged isAdult in their profile).

export const AVATARS: { emoji: string; adult: boolean }[] = [
  // Kids
  { emoji: "🐱", adult: false },
  { emoji: "🐶", adult: false },
  { emoji: "🐰", adult: false },
  { emoji: "🐻", adult: false },
  { emoji: "🐼", adult: false },
  { emoji: "🦊", adult: false },
  { emoji: "🐯", adult: false },
  { emoji: "🦁", adult: false },
  { emoji: "🐸", adult: false },
  { emoji: "🐵", adult: false },
  { emoji: "🦄", adult: false },
  { emoji: "🐲", adult: false },
  { emoji: "👶", adult: false },
  { emoji: "🧒", adult: false },
  { emoji: "👦", adult: false },
  { emoji: "👧", adult: false },
  { emoji: "💩", adult: false },
  { emoji: "🤡", adult: false },
  { emoji: "👽", adult: false },
  { emoji: "👻", adult: false },
  // Grown-ups
  { emoji: "🧔", adult: true },
  { emoji: "🧑", adult: true },
  { emoji: "👨", adult: true },
  { emoji: "👩", adult: true },
  { emoji: "🧓", adult: true },
  { emoji: "🥸", adult: true },
  { emoji: "🕵️", adult: true },
  { emoji: "👨‍🎤", adult: true },
  { emoji: "🥷", adult: true },
  { emoji: "🧙", adult: true },
  { emoji: "🦸", adult: true },
  { emoji: "🧞", adult: true },
  { emoji: "🧜", adult: true },
  { emoji: "🤴", adult: true },
  { emoji: "👸", adult: true },
  { emoji: "🫅", adult: true },
  { emoji: "🤵", adult: true },
];
