// v25w: scene system. Each scene = an illustrated background (sky +
// ground + decorative emoji) plus a curated grid of emoji tiles.
// Tapping a tile plays a random sound from that cluster's bucket.

import type { ReactNode } from "react";
import { CLUSTERS, type Cluster } from "./audio/clusterCatalog";

export type { Cluster };

export type SceneId = "farm" | "jungle" | "ocean" | "city" | "bedroom" | "bathroom";

export interface SceneDef {
  id: SceneId;
  name: string;
  emoji: string;
  sky: string;
  ground: string;
  decorations: Array<{ emoji: string; x: number; y: number; size?: number; opacity?: number }>;
}

export const SCENES: Record<SceneId, SceneDef> = {
  farm: {
    id: "farm", name: "Farm", emoji: "🌾",
    sky: "from-sky-300",
    ground: "to-lime-300",
    // v25w: illustrations handle most of the scene props now. We
    // keep just a couple of "pop" decorations for kid interaction.
    decorations: [
      { emoji: "🐝", x: 30, y: 22, size: 3, opacity: 0.9 },
      { emoji: "🦋", x: 75, y: 28, size: 3, opacity: 0.85 },
    ],
  },
  jungle: {
    id: "jungle", name: "Jungle", emoji: "🌴",
    sky: "from-emerald-300",
    ground: "to-emerald-700",
    decorations: [
      { emoji: "🦜", x: 80, y: 16, size: 4, opacity: 0.9 },
    ],
  },
  ocean: {
    id: "ocean", name: "Ocean", emoji: "🌊",
    sky: "from-sky-300",
    ground: "to-blue-700",
    decorations: [
      { emoji: "🐚", x: 25, y: 80, size: 2, opacity: 0.85 },
      { emoji: "🐟", x: 60, y: 70, size: 3, opacity: 0.8 },
    ],
  },
  city: {
    id: "city", name: "City", emoji: "🏙️",
    sky: "from-orange-200",
    ground: "to-zinc-600",
    decorations: [],
  },
  bedroom: {
    id: "bedroom", name: "Bedroom", emoji: "🛏️",
    sky: "from-indigo-400",
    ground: "to-indigo-600",
    decorations: [
      { emoji: "💤", x: 20, y: 70, size: 3, opacity: 0.85 },
    ],
  },
  bathroom: {
    id: "bathroom", name: "Bathroom", emoji: "🛁",
    sky: "from-cyan-200",
    ground: "to-blue-300",
    decorations: [
      { emoji: "🫧", x: 26, y: 38, size: 2, opacity: 0.85 },
      { emoji: "🫧", x: 70, y: 68, size: 2, opacity: 0.85 },
    ],
  },
};

export const SCENE_LIST: SceneDef[] = Object.values(SCENES);

export interface SceneLayout {
  scene: SceneDef;
  tiles: string[];
}

export const SCENE_LAYOUTS: Record<SceneId, SceneLayout> = {
  farm: {
    scene: SCENES.farm,
    tiles: [
      "animal:cow", "animal:pig", "animal:horse", "animal:sheep",
      "animal:goat", "animal:duck", "animal:rooster", "animal:bull",
      "animal:rabbit", "themed:machine",
    ],
  },
  jungle: {
    scene: SCENES.jungle,
    tiles: [
      "animal:elephant", "animal:lion", "animal:monkey", "animal:snake",
      "animal:bear", "animal:frog", "animal:hippo", "animal:turtle",
      "animal:bird", "animal:zebra",
    ],
  },
  ocean: {
    scene: SCENES.ocean,
    tiles: [
      "animal:whale", "animal:seal",
      "flavor:wet", "flavor:bubbly", "flavor:long", "flavor:echo",
      "themed:water", "themed:other",
    ],
  },
  city: {
    scene: SCENES.city,
    tiles: [
      "themed:machine", "themed:horn", "themed:boing",
      "flavor:dry", "flavor:squeaky", "flavor:long",
      "themed:brrt", "themed:scream", "themed:flute",
    ],
  },
  bedroom: {
    scene: SCENES.bedroom,
    tiles: [
      "themed:sleep", "animal:cat", "animal:dog",
      "themed:groan", "themed:breath", "themed:sneeze",
      "themed:cough", "themed:kiss",
    ],
  },
  bathroom: {
    scene: SCENES.bathroom,
    tiles: [
      "themed:toilet", "flavor:wet", "flavor:bubbly", "flavor:echo",
      "themed:water", "themed:other", "themed:groan",
    ],
  },
};

export function findCluster(id: string): Cluster | null {
  return CLUSTERS.find((c) => c.id === id) ?? null;
}

export interface SceneBackgroundProps {
  scene: SceneDef;
  children: ReactNode;
}

/** The page background for a scene. Renders the generated illustration
 *  as a full-bleed background image, then layers the decorative emoji
 *  on top, then the children (chips + tile grid).
 *
 *  Image path: /scenes/<id>.jpg (generated by
 *  scripts/generate-scenes.mjs and committed to public/scenes/). */
export function SceneBackground({ scene, children }: SceneBackgroundProps) {
  return (
    <div className="absolute inset-0 overflow-hidden">
      {/* Generated illustration as full-bleed background.
          The sky/ground Tailwind gradients from the SCENES def are used
          as fallback background-color while the image loads. */}
      <div
        className={"absolute inset-0 bg-cover bg-center " + scene.sky + " " + scene.ground}
        style={{
          backgroundImage: `url('/scenes/${scene.id}.jpg')`,
        }}
      />
      {/* Subtle dark scrim so the foreground text/emoji remain readable
          over the bright illustration. */}
      <div className="absolute inset-0 bg-black/10" />
      {/* Decorative emoji (sparse — most scene props come from the image) */}
      {scene.decorations.map((d, i) => (
        <div
          key={i}
          className="absolute pointer-events-none select-none"
          style={{
            left: d.x + "%",
            top: d.y + "%",
            fontSize: (d.size ?? 5) + "vw",
            opacity: d.opacity ?? 1,
            transform: "translate(-50%, -50%)",
            lineHeight: 1,
          }}
        >
          {d.emoji}
        </div>
      ))}
      <div className="relative h-full w-full flex flex-col">{children}</div>
    </div>
  );
}
